### ISSUE TITLE
Please link to libui in README

### ISSUE THREAD

**Issue by ssokolow** [rust-native-ui/libui-rs#20]
Currently, the README just says libui is cross-platform without elaborating, so my next step in determining whether this is relevant would be to visit libui for clarification and seeing no easy way to do that worsens the impression this project leaves on me.

Please provide a link to libui.

**Comment by NoraCodes** [comment]
We actually did have a link, but it is apparently broken.

**Comment by ssokolow** [comment]
The only links I see are the badges, "changelog", "how to contribute", and "@pcwalton"... none of which say "I'm a link to the website or repo for the native libui library that these crates bind to."
