### ISSUE TITLE
Examples for using DrawContext

### ISSUE THREAD

**Issue by alamminsalo** [rust-native-ui/libui-rs#24]
I can't seem to comprehend how I'm supposed to use the DrawContext (or where do I get uiDrawContext ptr for instancing new DrawContext). Quick example could help

**Comment by barzamin** [comment]
@LeoTindall this is blocked on the `area` mod not being exported from `controls::`, even though the source file exists. is this because it's incomplete/doesn't compile or something along those lines?

**Comment by NoraCodes** [comment]
No, it's not exported because it's not sufficiently documented, mostly because there are no examples. It's a totally circular dependency relationship there.

**Comment by barzamin** [comment]
@LeoTindall i was able to hack together the beginnings of an example, which i'll probably finish and PR soon :)

**Comment by pomettini** [comment]
Hi @barzamin would you mind to share what you discovered? I tried hard to make a simple example but had no luck. Thank you! :)

**Comment by barzamin** [comment]
@Pomettini my code is super WIP and requires changes to iui internals to work, but i'll try to post it in the next few days
