### ISSUE TITLE
Radio Buttons (Vertical and Horizontal)

### ISSUE THREAD

**Issue by LordZane** [rust-native-ui/libui-rs#27]

**Comment by NoraCodes** [comment]
This is definitely a feature we should implement. See `ui`'s impl at https://godoc.org/github.com/andlabs/ui#RadioButtons

**Comment by NoraCodes** [comment]
FYI, #29 is blocking this - as soon as I can get the bindgen version to build on Windows, we can start implementing all the new features, including this.

**Comment by barzamin** [comment]
i might try working on this over winter break from uni

**Comment by NoraCodes** [comment]
Would very much appreciate it! I'll be working on this project quite a bit over break as well.
