### ISSUE TITLE
libui since 13 June 2016 uses `int` instead of `intmax_t` in most functions

### ISSUE THREAD

**Issue by kennytm** [rust-native-ui/libui-rs#28]
... and this includes `uiNewSpinbox`.

(https://github.com/andlabs/libui/compare/857bbbf5062f86ef7c7ac175a1505b39088097e7...fa4542f217f1557490ba4b7dddf493ddf616b5d7)

In `iui 0.3.0`, `Spinbox::new_unlimited()` will forward to `Spinbox::new(i64::MIN, i64::MAX)`. However, as `uiNewSpinbox` takes the 32-bit `int` instead of the 64-bit `intmax_t`, the C library will truncate the numbers and read as `uiNewSpinbox(0, -1)`, which creates a spinbox with only two valid values: -1 and 0.

**Comment by NoraCodes** [comment]
Thanks, I'll address this shortly.
