### ISSUE TITLE
UIGrid Support

### ISSUE THREAD

**Issue by adals** [rust-native-ui/libui-rs#3]
hello
i have seen there is uigrid in the original libui so how to implement it in your libui-rs?

thanks

**Comment by NoraCodes** [comment]
As libui-rs is a wrapper, we can totally implement that! Could you give me some example code for using the uigrid, so I can think about the best way to write an API for it?

**Comment by andlabs** [comment]
https://github.com/andlabs/libui/blob/9785565c8cf3de5ff069094db6fa6a5a01695be9/examples/controlgallery/main.c#L247-L288 will result in what is shown at the right of https://i.imgur.com/6sg3gWh.png. The design of uiGrid is based on the design of GtkGrid, so its examples should map more or less directly...
