### ISSUE TITLE
No line breaks show in MultilineEntry

### ISSUE THREAD

**Issue by woelper** [rust-native-ui/libui-rs#37]
MultilineEntry does not display line breaks if those are supplied with set_value, such as
```
let mut mle = MultilineEntry::new(&ui);
mle.set_value(&ui, "hello\nworld");
```
The MultilineEntry will show `"helloworld"`.
The text returned from that MultilineEntry will be shown correctly with a line break when displayed with `println!("{}", mle.value(&ui));`

**Comment by NoraCodes** [comment]
This is very problematic, I'll look into it asap

**Comment by NoraCodes** [comment]
So, I've not had a lot of time to look at this, but, are you on Windows?

**Comment by woelper** [comment]
No worries, thanks for your help! Yes, I am on Windows indeed.

**Comment by NoraCodes** [comment]
I suspect this is because Windows wants `\r\n` line endings. Could you try that and let me know if it works?

**Comment by woelper** [comment]
I can confirm `mle.set_value(&ui, "hello\r\nworld");` works as expected, producing a line break in Windows.

**Comment by NoraCodes** [comment]
Possible solution: on Windows, the API can automatically replace `\n` with `\r\n`, and on other platforms, we'll do the inverse.
