### ISSUE TITLE
Get selected item from Combobox?

### ISSUE THREAD

**Issue by graynk** [rust-native-ui/libui-rs#39]
I'm looking at the documentation for Combobox control. I see a method to add items to combobox, I see a method to select an item and I see a method to create a callback that gets called on selected. But how do I actually GET selected item from combobox? `Entry` controls have `value()` method. What's the method for combobox? If I wanted to get the values from several comboboxes on the press of the button, would I really have to set `on_selected()` for each one and pass the data somewhere outside, to be collected in `on_clicked()` of the button?

**Comment by NoraCodes** [comment]
This was unavailable from `libui` when we last updated; as soon as the CMake stuff is finished this should get a working API.
