### ISSUE TITLE
Broken docs link: BoxExt doesn't exist

### ISSUE THREAD

**Issue by mitchhentges** [rust-native-ui/libui-rs#44]
The docs for [`HorizontalBox`](https://docs.rs/iui/0.3.0/iui/controls/struct.HorizontalBox.html) mention `BoxExt`:

> Lays out its children horizontally; see [BoxExt](https://docs.rs/iui/0.3.0/iui/controls/trait.BoxExt.html) for functionality.

Unfortunately, the trait `BoxExt` no longer exists, so clicking the `BoxExt` link doesn't work.
I would supply a PR to resolve this, but I'm still learning `iui`, so I'm not sure the correct solution (yet?)

**Comment by NoraCodes** [comment]
Yeah, we just need to remove that link. I'll do that when I have time soon.

**Comment by mitchhentges** [comment]
Ah, I'm not super familiar with the Rust documentation ecosystem, but I wish there was a way to see the most-recent `master` docs.

Well, I guess there's one way: check the source code!
This issue has been [solved already](https://github.com/LeoTindall/libui-rs/blob/master/CHANGELOG.md#fixed)

My bad :smile:
