### ISSUE TITLE
Is there a way to create a scrollable area?

### ISSUE THREAD

**Issue by chenshuiluke** [rust-native-ui/libui-rs#66]
I'm currently writing a program that will need to render long lists of stuff. Currently, the items extend off the screen. Is it possible to make a scrollable area?

**Comment by NoraCodes** [comment]
There is a `ScrollableArea` but, unfortunately, that doesn't do what you want. `libui` doesn't have a generic scrolling container yet, per andlabs/ui#253 and andlabs/libui#178

**Comment by chenshuiluke** [comment]
Hey, thanks for responding and for posting a follow up message on the scrollable area libui issue. I suppose you can close this for now, if you want

**Comment by boussou** [comment]
This is important feature, I hope we will see it appear some day. Any plan?

**Comment by chenshuiluke** [comment]
@boussou apparently it's something that would need to be implemented in the original libui library, before it can be implemented here. It seems that it will be implemented there after the Alpha 5 milestone is reached. There doesn't seem to be much progress on that as far as I can tell

**Comment by boussou** [comment]
Ok.
Wait and see then.
Thanks for the update.

**Comment by NoraCodes** [comment]
I imagine you're not still waiting on this, but for posterity let me explain that this is an issue with libui, on whom we depend; there's nothing we can do about it until they add this feature.

**Comment by boussou** [comment]
Ok, thanks for the followup

I had to do another way.

**Comment by RangerMauve** [comment]
How have folks been working around this limitation in the meantime? Not being able to scroll the UI seems like a non-starter for everything but the most basic UI.
