### ISSUE TITLE
Unresolved imports in `canvas` example

### ISSUE THREAD

**Issue by emlautarom1** [rust-native-ui/libui-rs#67]
I'm trying to run `/examples/canvas.rs`, but the specified imports are not available.
I get the following error:

```
unresolved imports `iui::controls::Area`, `iui::controls::AreaDrawParams`, `iui::controls::AreaHandler`
```

My `Cargo.toml` has the next dependencies:

```
[dependencies]
iui = "0.3.0"
ui-sys = "0.1.3"
```

I looked a bit into the `ui-sys` crate, and there seems to be an `Area`, `uiAreaDrawParams` and `uiAreaHandler`, yet replacing the original imports with those doesn't work, since `uiAreaHandler` is a `struct`, not a `trait`.

**-- Edit**

It seems that the proper traits are in the source code in the repo but not in `crates.io`.

**Comment by barzamin** [comment]
@lautaroem1 yeah, sorry, we still need to clean that code up and do a release (which is sitting on quite a few other blockers atm).

/cc @NoraCodes

**Comment by NoraCodes** [comment]
Aaaand it's been a year, almost. But 0.4.0 is coming!

**Comment by Legend-of-iPhoenix** [comment]
Any updates on this? I had the exact same problem under the exact same circumstances.
