### ISSUE TITLE
Examples: Slider and spinner start at 1, but underlying code thinks it's 0

### ISSUE THREAD

**Issue by nyanpasu64** [rust-native-ui/libui-rs#75]
For inputs.rs and inputs-grid.rs, the slider and spinner start at 1, but the code (slider_val and spinner_val) thinks it's 0. Clicking the slider tells the underlying code (add/subtract) it's 1, and changing the spinner to 2 tells the underlying code (add/subtract) it's 2.

**Comment by NoraCodes** [comment]
Well that's a silly error on my part.

**Comment by NoraCodes** [comment]
Oh, this actually looks like a libui error - I'll raise that there. For now I can add a simple hack to get around this.
