### ISSUE TITLE
Examples: examples with progressbar don't work

### ISSUE THREAD

**Issue by legendiguess** [rust-native-ui/libui-rs#79]
Compiler in examples can't find progressbar. More then - even i can't find it. Docs says that iui don't have progressbar at all(i can't find anything that contains Progress or something).
I took this example - https://github.com/rust-native-ui/libui-rs/blob/master/iui/examples/inputs.rs
Compiler errors:
![image](https://user-images.githubusercontent.com/40376451/69908453-b01b5b00-140b-11ea-96e7-9b7a9929452b.png)
![image](https://user-images.githubusercontent.com/40376451/69908446-91b55f80-140b-11ea-842c-0f3bb145ed76.png)
Using `iui v0.3` and `ui-sys v0.1.3`

**Comment by barzamin** [comment]
`ProgressBar` isn't in `iui v0.3`; it's only in the current git master. We need to do another release at some point, haha
