### ISSUE TITLE
uiComboboxSelected is missing in iui

### ISSUE THREAD

**Issue by zoumi** [rust-native-ui/libui-rs#82]
I can not find Selected() method for Combobox in library, but it  exiests in ui-sys crate.

**Comment by zoumi** [comment]
Why not export ui_sys crate in iui crate? Sometimes we need call raw apis because iui does not wrap them.

**Comment by zoumi** [comment]
selected() is already added in master branch.

**Comment by NoraCodes** [comment]
Hey. Just wanted to drop in and say, I am sorry for not being more active with updating this project. I'm planning to return to it but am currently in the last semester of my university degree in computer science, and am hunting for jobs, so I do not have a lot of free time.

Please use master branch for now, and I will cut a release as soon as I have time to review some pull requests.
