### ISSUE TITLE
Define Rust MSRV

### ISSUE THREAD

**Issue by xobs** [rust-native-ui/libui-rs#87]
It would be nice if libui had a Minimum Supported Rust Version.

When building iui with 

For example, ATOMIC_BOOL_INIT (used in `iui/src/ffi_tools.rs`) was deprecated in Rust 1.34, and users were asked instead to use `AtomicBool::new() which appeared in Rust 1.32.

Additionally, `mem::uninitialized` was deprecated in Rust 1.39 due to its unsoundness, preferring `mem::MaybeUninit` which was introduced in Rust 1.36.

I have patches to fix these, but it bumps the MSRV up to 1.36 in order to use `MaybeUninit`.

**Comment by NoraCodes** [comment]
I'm inclined to set the MSRV to 1.40; I want the macro improvements and #[non_exhaustive] for future API refactoring. I'm open to other opinions, though.

**Comment by NoraCodes** [comment]
Given that there haven't been comments, I'm going to set the MSRV to 1.40.
