### ISSUE TITLE
Disable/Remove window buttons

### ISSUE THREAD

**Issue by sinasalek** [rust-native-ui/libui-rs#90]
Is it possible to disable or remove window buttons like close, minimize, maximize?

**Comment by LoganDark** [comment]
You mean like making the window borderless? Or keeping the titlebar and simply disabling individual ones like the close button?

**Comment by sinasalek** [comment]
For example disabling or removing x(close) button

**Comment by NoraCodes** [comment]
This is not a capability of `libui`, on which we are based. If that feature becomes available, we will consider implementing it.
